# Generated by Django 4.0.5 on 2022-06-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_remove_apkpayload_apk_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='dump_sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_type', models.CharField(blank=True, default='', max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(blank=True, default='', max_length=100)),
                ('body', models.TextField()),
            ],
        ),
    ]
