# Generated by Django 4.0.5 on 2022-06-21 18:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_dump_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
    ]
