# Generated by Django 4.0.5 on 2022-07-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_alter_messages_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='dump_sms',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
