# Generated by Django 4.0.5 on 2022-07-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_dump_sms_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dump_sms',
            name='sms_type',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2)], max_length=50),
        ),
    ]
