# Generated by Django 4.0.5 on 2022-07-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_alter_dump_sms_sms_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dump_sms',
            name='sms_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
